### ISSUE TITLE
Lighthouse Teleport is weird

### ISSUE THREAD

**Issue by Chiefwaffles** [MemoryPenguin/Survival-303-Issues#2]
Positioning/teleport method needs to be changed. As it stands, 95% of the time, the player is teleported to the top of the lighthouse instead of the hatch.

**Comment by MemoryPenguin** [comment]
Pretty sure that's because of clearance at the top of the lighthouse.  It's using MoveTo, so if the player has hats on that make them too tall to fit (even if said hats don't collide), they end up on top.

**Comment by Chiefwaffles** [comment]
Can be solved with a torso frame change (and quick calculations to adjust for height) or just raising the roof.

**Comment by MemoryPenguin** [comment]
Raising the height isn't a permanent solution; if more hats are added, that could break it again - I'd rather not revisit this in three months.  There shouldn't be a need to calculate the character's height since hats don't collide, so just set the CFrame to `teleport.CFrame + Vector3.new(0, 3, 0)`.

**Comment by MemoryPenguin** [comment]
Fixed in dev; will be pushed with v6.27.
